const menuItems = [
  {
    id: 1,
    category: "Ramen",
    name: "Spicy Vegan Ramen",
    description: "Delicious vegan ramen",
    image: "../public/assets/Iteration-2-assets/pictures/ramen1.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
  {
    id: 2,
    category: "Ramen",
    name: "Miso Ramen Delight",
    description: "Rich miso ramen with a twist",
    image: "../public/assets/Iteration-2-assets/pictures/ramen2.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
  {
    id: 3,
    category: "Ramen",
    name: "Shoyu Ramen Special",
    description: "Traditional Japanese Shoyu Ramen",
    image: "../public/assets/Iteration-2-assets/pictures/ramen3.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
  {
    id: 4,
    category: "Pizza",
    name: "Pepperoni Fire Pizza",
    description: "Spicy pepperoni pizza",
    image: "../public/assets/Iteration-2-assets/pictures/food-1.png",
    rating: 4.5,
    ordersCount: 120,
    price: 129.9,
  },
  {
    id: 5,
    category: "Pizza",
    name: "Margherita Classic",
    description: "Classic Margherita pizza",
    image: "../public/assets/Iteration-2-assets/pictures/food-2.png",
    rating: 4.7,
    ordersCount: 85,
    price: 600,
  },
  {
    id: 6,
    category: "Pizza",
    name: "BBQ Chicken Special",
    description: "Classic BBQ chicken pizza",
    image: "../public/assets/Iteration-2-assets/pictures/pizza3.png",
    rating: 4.6,
    ordersCount: 150,
    price: 600,
  },
  {
    id: 7,
    category: "Burger",
    name: "Vegan Delight Burger",
    description: "Delicious vegan burger",
    image: "../public/assets/Iteration-2-assets/pictures/food-3.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
  {
    id: 8,
    category: "Burger",
    name: "BBQ Beef Burger",
    description: "Delicious BBQ beef burger",
    image: "../public/assets/Iteration-2-assets/pictures/burger1.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
  {
    id: 9,
    category: "Burger",
    name: "Classic Cheeseburger",
    description: "Classic cheeseburger",
    image: "../public/assets/Iteration-2-assets/pictures/burger2.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
  {
    id: 10,
    category: "French fries",
    name: "Crispy Fries",
    description: "Delicious crispy fries",
    image: "../public/assets/Iteration-2-assets/pictures/pk1.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
  {
    id: 11,
    category: "French fries",
    name: "Cheesy Fries",
    description: "Delicious cheesy fries",
    image: "../public/assets/Iteration-2-assets/pictures/pk2.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
  {
    id: 12,
    category: "French fries",
    name: "Garlic Butter Fries",
    description: "Delicious garlic butter fries",
    image: "../public/assets/Iteration-2-assets/pictures/pk3.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
  {
    id: 13,
    category: "Fast Food",
    name: "Vegan Delight Burger",
    description: "Delicious vegan burger",
    image: "../public/assets/Iteration-2-assets/pictures/food-3.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
  {
    id: 14,
    category: "Fast Food",
    name: "Spicy Beef Burger",
    description: "Delicious spicy beef burger",
    image: "../public/assets/Iteration-2-assets/pictures/food-1.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
  {
    id: 15,
    category: "Fast Food",
    name: "Grilled Chicken Burger",
    description: "Grilled chicken burger with sauce",
    image: "../public/assets/Iteration-2-assets/pictures/food-2.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
  {
    id: 16,
    category: "Soft drinks",
    name: "Sparkling Water",
    description: "Refreshing sparkling water",
    image: "../public/assets/Iteration-2-assets/pictures/sd1.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
  {
    id: 17,
    category: "Soft drinks",
    name: "Cola",
    description: "Classic cola drink",
    image: "../public/assets/Iteration-2-assets/pictures/sd2.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
  {
    id: 18,
    category: "Soft drinks",
    name: "Lemonade",
    description: "Freshly squeezed lemonade",
    image: "../public/assets/Iteration-2-assets/pictures/sd3.png",
    rating: 4.8,
    ordersCount: 70,
    price: 99.9,
  },
];

export default menuItems;
